name: Update WakaTime README

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC every day
    - cron: "0 0 * * *"

jobs:
  update-wakatime-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@ebb9e39b510045d5044c4453bf4708adcdfbfd8e
        with:
            WAKATIME_API_KEY: '${{ secrets.WAKATIME_API_KEY }}'
            GH_TOKEN: '${{ secrets.GH_TOKEN }}'
            SYMBOL_VERSION: '2'
            SHOW_LANGUAGE: 'True'
            SHOW_OS: 'True'
            SHOW_EDITORS: 'True'
